<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Properti_BTN_Data_Binding_Positif</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b98b2fc1-f018-4aca-a258-91cd735c06b1</testSuiteGuid>
   <testCaseLink>
      <guid>895fdc63-0ddf-4703-9236-8cd327985ae9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Positif/TC2 - Positif_ BTN_Data_binding</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>de6ddf74-241b-4bfb-aaea-f0346b100f8f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Excel Positif</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>de6ddf74-241b-4bfb-aaea-f0346b100f8f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>penghasilan</value>
         <variableId>436fa101-1c55-4492-9c99-49ca17285e5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>de6ddf74-241b-4bfb-aaea-f0346b100f8f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pengeluaran</value>
         <variableId>e96e0fec-802b-42b1-b11f-cc00325dda38</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>de6ddf74-241b-4bfb-aaea-f0346b100f8f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>jangkaWaktu</value>
         <variableId>1597a2df-2a33-4818-8edb-aeca156b7e5c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
