<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Properti_BTN_Data_Binding_Negatif</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c6bce5b7-6210-40a8-84b9-229a28fb21ac</testSuiteGuid>
   <testCaseLink>
      <guid>895fdc63-0ddf-4703-9236-8cd327985ae9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Negatif/TC2-Negatif Data Binding BTN</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f04b6df8-d20d-49ce-8134-d137a07d3556</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Data Excel Negatif</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f04b6df8-d20d-49ce-8134-d137a07d3556</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>penghasilan</value>
         <variableId>14fd7b23-9e6b-4aa8-8124-5b9d98d6c50a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f04b6df8-d20d-49ce-8134-d137a07d3556</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>pengeluaran</value>
         <variableId>ba025b88-1f37-406e-99a1-72052b992c47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f04b6df8-d20d-49ce-8134-d137a07d3556</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>jangkaWaktu</value>
         <variableId>789d840b-444e-48aa-849d-b5d1eadf74cd</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
