<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Langsung cari di area yang kamu inginkan</name>
   <tag></tag>
   <elementGuidId>233170bf-3b35-47cc-8dfd-afdba7f2cc27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#harga_hasil > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='harga_hasil']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>21b5199c-3335-481f-b4ae-33400778166b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Langsung cari di area yang kamu inginkan</value>
      <webElementGuid>02068df8-3102-48c0-97d5-0d134958dcc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;harga_hasil&quot;)/p[1]</value>
      <webElementGuid>08529266-3ea4-451a-97f3-bd045607987d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='harga_hasil']/p</value>
      <webElementGuid>bd06495a-68bf-4252-b3e0-be9c620690c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harga Properti Maksimal Kamu'])[1]/following::p[1]</value>
      <webElementGuid>2d9e0fcb-f69b-40a9-ac6d-a37fa158aba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lokasi'])[1]/preceding::p[1]</value>
      <webElementGuid>18dff05e-88ce-401a-a500-243546ca9044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARI PROPERTI'])[1]/preceding::p[1]</value>
      <webElementGuid>4c3e5daf-bfb6-45e0-9485-61672158fbe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Langsung cari di area yang kamu inginkan']/parent::*</value>
      <webElementGuid>365233ac-557d-4a49-93f6-941f71274e95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/p</value>
      <webElementGuid>f43c47fc-d5cc-47de-b38c-edf259c2326f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Langsung cari di area yang kamu inginkan' or . = 'Langsung cari di area yang kamu inginkan')]</value>
      <webElementGuid>459df7bc-2d35-46cc-829d-2829b690aae3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
